// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"GoGinStarter/app/repositories/otp"
	"GoGinStarter/app/repositories/user"
	otp2 "GoGinStarter/app/services/otp"
	user2 "GoGinStarter/app/services/user"
	"GoGinStarter/internal/cache"
	"GoGinStarter/internal/config"
	"GoGinStarter/internal/container"
	"GoGinStarter/internal/db"
	"GoGinStarter/internal/event"
	"GoGinStarter/internal/log"
	"GoGinStarter/internal/response"
	"GoGinStarter/internal/scheduler"
	"GoGinStarter/internal/seeder"
	"GoGinStarter/internal/session"
)

// Injectors from wire.go:

func InitializeContainer() *container.Container {
	logLog := log.ProvideLog()
	configConfig := config.ProvideConfig(logLog)
	gormDB := db.ProvideDB(configConfig, logLog)
	repository := otp.ProvideOtpRepository(gormDB, logLog, configConfig)
	cacheCache := cache.ProvideCache(configConfig, logLog)
	dispatcher := event.ProvideDispatcher()
	service := otp2.ProvideOTPService(repository, logLog, cacheCache, dispatcher)
	userRepository := user.ProvideUserRepository(gormDB, logLog)
	userService := user2.ProvideUserService(userRepository, logLog, cacheCache, dispatcher)
	responseResponse := response.ProvideResponse()
	seederSeeder := seeder.ProvideSeeder(gormDB)
	sessionSession := session.ProvideSession(gormDB)
	schedule := scheduler.ProvideSchedule()
	containerContainer := container.ProvideContainer(service, repository, userService, userRepository, cacheCache, configConfig, gormDB, responseResponse, logLog, dispatcher, seederSeeder, sessionSession, schedule)
	return containerContainer
}
