// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"GoGinStarter/app/repositories/user"
	user2 "GoGinStarter/app/services/user"
	"GoGinStarter/internal/cache"
	"GoGinStarter/internal/config"
	"GoGinStarter/internal/container"
	"GoGinStarter/internal/db"
	"GoGinStarter/internal/event"
	"GoGinStarter/internal/log"
	"GoGinStarter/internal/response"
)

// Injectors from wire.go:

func InitializeContainer() *container.Container {
	logLog := log.ProvideLog()
	configConfig := config.ProvideConfig(logLog)
	gormDB := db.ProvideDB(configConfig, logLog)
	repository := user.ProvideUserRepository(gormDB, logLog)
	cacheCache := cache.ProvideCache(configConfig, logLog)
	dispatcher := event.ProvideDispatcher()
	service := user2.ProvideUserService(repository, logLog, cacheCache, dispatcher)
	responseResponse := response.ProvideResponse()
	containerContainer := container.ProvideContainer(service, repository, cacheCache, configConfig, gormDB, responseResponse, logLog, dispatcher)
	return containerContainer
}
